### ISSUE TITLE
Tweaks for interface deployment needed

### ISSUE THREAD

**Issue by rzelayafavila** [greenelab/tribe#12]
Today, when doing a new deployment, I needed to run the following commands manually:

a) Once the `initial_setup_and_check` command in the fabfile created the symlink to the static folder (via the private method `_make_static()`), I needed to run (from inside the `/tribe/tribe` folder): 
`ln -s ../static/index.html templates/index.html` to create the symlink to the index.html file for django to use.

b) Also, the `deploy` fabfile command asked me to pick between `spin.js` versions - `2.0.0` and `2.1.0`. I chose `2.1.0`.

However, both of these steps should not be run manually, they should be automated in the deployment process.

**Comment by dongbohu** [comment]
Suppose the working directory (also the web server's root dir and where the github repo is cloned) is `/home/user/tribe`, then `fabfile.py` shows that `initial_setup_and_check` only creates this link:

```/home/user/tribe/static ---> /home/user/tribe/interface/bin/```

But according to line 30 of `/home/user/tribe/tribe/urls.py`:

```ensure_csrf_cookie(TemplateView.as_view(template_name="index.html")),```

The following file is required in order to show the main page:

```/home/user/tribe/tribe/templates/index.html```

By the way, the command that Rene wrote was incorrect, it should be:

```ln -s ../../static/index.html templates/index.html```

because `static` is located in `/home/user/tribe/`, see my explanation in the first paragraph.

I am surprised that this issue didn't show up in previous deployment(s).

**Comment by dongbohu** [comment]
The soft links were built in tribe-ec2-deploy in this PR:
https://bitbucket.org/greenelab/tribe-ec2-deploy/pull-requests/5/two-more-deployment-steps/diff

The issue of `spin.js` versions is addressed by PR #22.
